### ISSUE TITLE
Missing model

### ISSUE THREAD

**Issue by 7ranceaddic7** [Kerbas-ad-astra/Stock-Revamp#21] opened 2020-07-09 01:48 UTC
[ERR 16:12:54.890] PartCompiler: Cannot clone model 'VenStockRevamp/Squad/Parts/IVA/ExitHandle' as model does not exist

I've done some digging and it looks like this model just never got created,

**Comment by Kerbas-ad-astra** [comment] 2020-12-31 01:51
Thanks for the heads-up, fixed by f351df8 (and a few similar errors caused by similarly unfinished prop models).

**Closed by Kerbas-ad-astra** 2020-12-31 01:51 UTC
